name: Deploy React App to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Starting Deployment
      run : echo "Starting Deployment"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      working-directory: frontend

    - name: Build the React app
      run: npm run build
      env:
        CI: false
      working-directory: frontend

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1
        S3_BUCKET_NAME: mchouhan.co.in
      working-directory: frontend
      run: |
        npm install -g aws-cli
        aws s3 sync build/ s3://$S3_BUCKET_NAME --delete

    - name: Invalidate CloudFront cache
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1
        DISTRIBUTION_ID: E3LQ59LLO0KK94
      run: |
        aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Starting Deployment
      run : echo "Starting Deployment"
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      working-directory: backend
    
    - name: Package application
      run: zip -r backend.zip backend/

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      
    - name: Upload package to EC2
      run: |
        echo "Uploading package to EC2"
        scp -o StrictHostKeyChecking=no backend.zip ec2-user@ec2-65-0-134-114.ap-south-1.compute.amazonaws.com:/home/ec2-user/ || { echo "SCP failed"; exit 1; }
  
    - name: Deploy and run backend
      run: |
        echo "Restarting Services"
        cat cloud/ec2RestartScript.sh | ssh ec2-user@ec2-65-0-134-114.ap-south-1.compute.amazonaws.com || { echo "SSH command failed"; exit 1; }